### ISSUE TITLE
Configuring Jinja2 extensions

### ISSUE THREAD

**Issue by miracle2k** [niwinz/django-jinja#117]
Jinja2 has this idea that when extensions need configuration, it should be done by setting attributes on the environment. It seems to be that this is currently pretty hard - I am doing this now:

```
from jinja2 import Environment as Jinja2Environment
class ConfiguredJinja2Environment(Jinja2Environment):
    def __init__(self, *a, **kw):
        Jinja2Environment.__init__(self, *a, **kw)
        from django_assets.env import get_env
        self.assets_environment =   get_env()

TEMPLATES = [
{
    "BACKEND": "django_jinja.backend.Jinja2",
    "OPTIONS": {
        "environment": 'myproject.settings.ConfiguredJinja2Environment',
```

**Comment by niwibe** [comment]
I'm not pretty sure that this approach is really good idea, independently of how jinja2 convention is :S

**Comment by miracle2k** [comment]
http://jinja.pocoo.org/docs/dev/extensions/#jinja2.ext.Extension

> As extensions are created by the environment they cannot accept any arguments for configuration.    One may want to work around that by using a factory function, but that is not possible as extensions are identified by their import name. The correct way to configure the extension is storing the configuration values on the environment. 

So there really isn't any other way, and some extensions will need configuration. See also for example the fragment extension example in the Jinja2 docs.

**Comment by niwibe** [comment]
I understand... I will think something for solve it.

**Comment by niwibe** [comment]
I think that an other solution for this is some kind of hook, that will be called when all environment is up and running, that hook will receive the environment. This will decouple a little bit the environent from the configurations of third party extensions.

That do you think?

**Comment by miracle2k** [comment]
I like the idea. I don't necessarily buy the decoupling argument, but since Jinja doesn't have an API for this and you are essentially just making an arbitrary modification of the environment objects, it seems just as well that the user should do this in code, not via some interface.

**Comment by wizpig64** [comment]
closing this as it's 7 years old.
