### ISSUE TITLE
Test suite included with sdist and run with "setup.py test"

### ISSUE THREAD

**Issue by EdwardBetts** [niwinz/django-jinja#135]
I have two suggestions for the tests in the testing directory.

I would like the testing directory to be included when runnning setup.py sdist.

Can you make the test suite runable using "setup.py test"?

Thanks.

**Comment by niwinz** [comment]
Sincerelly I don't understandy why the tests should be included in sdist. They are only for development purposes.

**Comment by EdwardBetts** [comment]
I built and updated a Debian package of django-jinja, it is available here:

https://tracker.debian.org/pkg/django-jinja

Debian Python packages are built from the tarball uploaded to pypi. It is useful to run the test suite when building the Debian package, to ensure that the code is working correctly.

**Comment by niwinz** [comment]
I understand, but it also implies that you should will be able run tests with setup.py test and currently it is not possible... 

Lamentably it is a very low priority task for me and additionally I don't like run tests through the setup.py...
