### ISSUE TITLE
Context processor support not working?

### ISSUE THREAD

**Issue by tylereaves** [niwinz/django-jinja#137]
My custom context processor is not being called.

It imports and runs fine from shell, but in template variables are undefined.

Django 1.8.3/4 and d_j 1.4.1

TEMPLATES = [{
 'BACKEND': 'django_jinja.backend.Jinja2',
  'DIRS': ['/webapps/dbt/templates/',],
   'APP_DIRS': False,
'OPTIONS':{'context_processors': ['setlist.context_processors.tour_processor'],'match_extension':'.jinja'}
},

**Comment by niwinz** [comment]
Can you explain how you are rendering the templates? This may determine if is a user bug or django-jinja bug.
