### ISSUE TITLE
makemessages does not grab translation string in template

### ISSUE THREAD

**Issue by SimonSteinberger** [niwinz/django-jinja#138]
It's a rather exotic thing and I'm not sure if that's a Django bug or a django-jinja issue. Having this rather unusual structure in a template, makemessages isn't able to grab the second translation string:

    {{ bool and _("Translate me 1") or _("Translate me 1") }}

`bool` can be any expression returning `True` or `False`.

It works properly though by using an extra if statement:

    {% if bool %}{{ _("Translate me 1") }}{% else %}{{ _("Translate me 2") }}{% endif %}

**Comment by niwinz** [comment]
This is something that we should deal with it. Django 1.8 fixes some problems of the messages parser that have found on django <= 1.7 but not all issues are fixed.

The recommeded way to setup messages since django 1.8 is using babel.
