### ISSUE TITLE
Multiple template backend causes django-jinja loaders to be overridden

### ISSUE THREAD

**Issue by rossmiller** [niwinz/django-jinja#139]
Hi there,

We have been looking at the django-jinja project as a way of increasing the performance of template rendering within our project. We have set up multiple template back ends in order to try Jinja2 templates for a small percentage of the templates used within the site and bench mark their performance against the standard Django template system. We are having an issue where changes to the loaders option for the Django template setting is affecting the django-jinja loader setting.

```
TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [
                ...
        ],
        'OPTIONS': {
            'match_extension': '.jinja',
            'context_processors': [
                ...
            ],
        }
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            ...
        ],
        'OPTIONS': {
            'context_processors': [
                ...
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ]
        },
    },
]
```

The addition of the following (to turn off caching for local development) affects the django-jinja logic, in that, caching is also turned off for jinja2 templates.

```
TEMPLATES[1]['OPTIONS']['loaders'] = [
     'django.template.loaders.filesystem.Loader',
     'django.template.loaders.app_directories.Loader',
]
```

This occurs whether or not the django-jinja template loader (shown below for clarity) is present in the configuration.

```
TEMPLATE_LOADERS = (
    'django_jinja.loaders.FileSystemLoader',
    'django_jinja.loaders.AppLoader',
)
```

**Comment by niwinz** [comment]
The jinja templates are slightly different from django so you can't just render django templates with jinja. Later, django-jinja works like middleware and intercepts by default by extension. If you keep your templates as is, with html file extension they are just ignored by django-jinja and rendered with the django templates engine.
