### ISSUE TITLE
django-widget-tweaks integration

### ISSUE THREAD

**Issue by sandroden** [niwinz/django-jinja#140]
Just started with jingjia and django-jinjia. I'd like to "translate" some templates that used add_class from widget_tweaks to simply add lcasses to fields. Is there a way to use django-widget-tweaks or is there another way to do it? I see there is an old closed ticket (#8) that place the same question, bu w/o answer...

thanks in advance
sandro
*:-)

**Comment by Naddiseo** [comment]
If you're using django >=1.8 you can add django-widget-tweaks' filters via the options.

Something like this in your django settings.py:
```
TEMPLATES = [
	{
		'BACKEND': 'django_jinja.backend.Jinja2',
		'OPTIONS': {
			'filters': {
				'add_class': 'widget_tweaks.templatetags.widget_tweaks.add_class',
				'set_attr': 'widget_tweaks.templatetags.widget_tweaks.set_attr',
			},
			'globals': {
				...
			},
			'context_processors': [
				...
			],
		}
	},
]```

If it's for django < 1.8, you can import the jinja environment from django-jinja, then add the filters to the environment.

**Comment by sandroden** [comment]
Works like a charm. Thanks. Just to be sure I understand what that implies. Is this a general way to register a function as a filter? It does not relay on the fact that add_class was already registered in django, i guess... is it equivalent to registering via django_jinjia.library.filter decorator?

**Comment by Naddiseo** [comment]
It's the general way: [docs here](http://niwinz.github.io/django-jinja/#_custom_filters_globals_constants_and_tests).

**Comment by niwinz** [comment]
You have the django like autoloading: http://niwinz.github.io/django-jinja/#_registring_filters_in_a_django_way for register additional functions or the undocumented setting `JINJA2_GLOBALS` (see #141)

**Comment by rob101** [comment]
How do you use this in the template? eg `{% render_field field class="form-control" %}` results in 

> Encountered unknown tag 'render_field'. Jinja was looking for the following tags: 'endif'. The innermost block that needs to be closed is 'if'.

**Comment by wizpig64** [comment]
@rob101 I suspect you want to register `render_field` as a global function:

```
TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'OPTIONS': {
            'filters': {
                ...
            },
            'globals': {
                'render_field': 'widget_tweaks.templatetags.widget_tweaks.render_field',
            },
            'context_processors': [
                ...
            ],
        }
    },
]
```

Then your jinja code will to change to something like `{{ render_field(field, class="form-control") }}`.
