### ISSUE TITLE
Some settings are undocumented

### ISSUE THREAD

**Issue by akheron** [niwinz/django-jinja#141]
JINJA2_ENVIRONMENT_OPTIONS seems totally undocumented.

In addition, the following are undocumented in Django <=1.7 user guide, though briefly documented in the Django >=1.8 user guide.
- JINJA2_UNDEFINED
- JINJA2_CONSTANTS
- JINJA2_TRANSLATION_ENGINE
- JINJA2_NEWSTYLE_GETTEXT
- JINJA2_TESTS
- JINJA2_FILTERS
- JINJA2_GLOBALS
- JINJA2_CONSTANTS

My question is that should these be documented or is it intentional that they have been left undocumented?

**Comment by niwinz** [comment]
Hi @akheron 

Yes, would be awesome have them documented. PR are very welcome! :D

**Comment by niwinz** [comment]
Now them are only for the 1.x branch and I do not expect have them documented. The development is focused on 2.x branch that is only targets to django >= 1.8 and it does not uses that settings.
