### ISSUE TITLE
support for django-debug-toolbar

### ISSUE THREAD

**Issue by sandroden** [niwinz/django-jinja#143]
I'm trying jinjia templated for the first time . I noticed that django-debug-toolbar works but not for templates.It does not show neather the templates used nor the context. Is there some configuration option that I have not seen.

I noticed an old (1 year) message that seemd to state it'd perfectly supported...

TIA
sandro
*:-)

**Comment by niwinz** [comment]
The templates loading of jinja is very different from the django templates and django-debug-toolbar does not have support for it. I think we can't do nothing in django-jinja for it. ddt should add support for it I think...
