### ISSUE TITLE
Unclear how match_regex works

### ISSUE THREAD

**Issue by Suor** [niwinz/django-jinja#144]
If I do not use `match_extension`, but have `"match_regex": r'.*\.(j2|jinja)$',` then it doesn't really works. This is because `match_extension` is still there being default and it makes regex match useless. This is unclear, undocumented and inconsistent with how django_jinja with Django 1.7 works.

So either behavior or docs should be updated.

**Comment by Suor** [comment]
P.S. the workaround is set `match_extension` to `None`, which looks weird, but works.

**Comment by niwinz** [comment]
The both settings are working together, is that expected. If you don't want match_extension you can disable it in the way as you call "workaround". Maybe the docs should be a little bit clear.
