### ISSUE TITLE
Tag 1.4.2 release

### ISSUE THREAD

**Issue by stevelacey** [niwinz/django-jinja#153]
Extensions can't be registered due to the bug fixed in https://github.com/niwinz/django-jinja/commit/b7579ae1b5deff6afb937c3bb07b576b4cb4fe00 which was committed after 1.4.1

Can you tag a new release and push it up to PyPi

**Comment by stevelacey** [comment]
@niwinz any chance you can take a look at this? I am installing from repo until then :confused:

**Comment by niwinz** [comment]
Done! Sorry for my late response.

**Comment by stevelacey** [comment]
Thanks!
