### ISSUE TITLE
Adding documentation and changelog to pypi tar.gz

### ISSUE THREAD

**Issue by EdwardBetts** [niwinz/django-jinja#160]
Hi,

I'd like to include the module documentation and changelog in the Debian package. The package is built from the pypi release tar.gz

Please can you add the documentation and changelog to the tar.gz that you upload to pypi.

Thanks,

Edward.

**Comment by niwinz** [comment]
Sorry for not answer this before. It is not very priority issue for me but feel free to open a PR with that changes and I gladly accept it.
