### ISSUE TITLE
Release latest Django 1.8 fixes on PyPI

### ISSUE THREAD

**Issue by boydjj** [niwinz/django-jinja#164]
The current release on PyPI, 2.1.1, contains an error fixed in cfc247e494488cc6f350bee4843f441c64073047. We're switching to use the GH master for now, but a PyPI release would be great.

Thanks for maintaining this package. :)

**Comment by akx** [comment]
+1 for a bugfix release! :)

**Comment by niwinz** [comment]
I will do it today!
