### ISSUE TITLE
django 1.9.x warning TEMPLATE_* in settings

### ISSUE THREAD

**Issue by RaminFP** [niwinz/django-jinja#167]
with Django 1.9.2 and TEMPLATE_DEBUG set in settings.py you now get:

```shell
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
```

**Comment by niwinz** [comment]
I'm not clearly understand this issue, can you explain your problem a little bit more?

**Comment by RaminFP** [comment]
when i will use custom error i set in settings.py work for me custom error but i get this warnning :
```python
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = DEBUG
```
when i run application i see this warning,
```shell
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
```
i use ```python TEMPLATES = DEBUG ``` nothing of warning ,

**Comment by niwinz** [comment]
Seems like something unrelated to django-jinja. TEMPLATE_DEBUG is a deprecated settings, if you set it, the waring is raised by django. I suggest do not use TEMPLATE_DEBUG settings.

In any case seems completely unrelated to django-jinja.
