### ISSUE TITLE
"context" variable not being populated anymore in test client's response

### ISSUE THREAD

**Issue by duduklein** [niwinz/django-jinja#170]
I used to install django-jinja at commit 361c001dc6d3918e861071b619c77b84f9ed8f64 (between versions 1.4.1 and 1.4;2).

Using the test client (django 1.8), I was able to access the response.context variable correctly.
I updated to the latest version of django-jinja and tests started to fail. I downgraded the versions until 1.4.2 and it still fails.

So the issus was created in a commit between the one above and the release of 1.4.2. 

I also found, while I was looking for this issue a ticket at the django project, that may be related: https://code.djangoproject.com/ticket/24622

Do you know what could be causing this issue?
Thanks in advance,

**Comment by niwinz** [comment]
This seems that the signal is emited only if template debug is activated: https://github.com/niwinz/django-jinja/blob/master/django_jinja/backend.py#L101
by default is set to settings.DEBUG, that is `False` in test invironment as far as I know, so you should set it explicitly to `True`.

**Comment by duduklein** [comment]
This behavior seems to be new (commit 7b605259c180). I don't know how it worked before. This commit is between the ones I mentioned in the ticket description.

According to django's docs: "Regardless of the value of the DEBUG setting in your configuration file, all Django tests run with DEBUG=False. This is to ensure that the observed output of your code matches what will be seen in a production setting." I took this from https://docs.djangoproject.com/en/1.9/topics/testing/overview/#other-test-conditions .

So it seems contradictory for me to set debug false in order to make the test client work properly. 
What do you think?

**Comment by niwinz** [comment]
You have not understand me. templte debug settings is not the same as settings.DEBUG. `django-jinja` by default setups template debug prop as the settings.DEBUG but it can be overwritten.

Which version of django-jinja, and django you are using?

**Comment by duduklein** [comment]
I'm using django 1.8 and the latest django-jinja (2.1.2, I think).

I know that settings.DEBUG is not the same as the TEMPLATE_DEBUG (which is now by template engine), but it's the same logic: all the debugs should be disabled in the tests to ensure the correct output in production.

I can actually overwrite only the template_debug to have the context variable but it can have other side effects that I can not predict.

**Comment by niwinz** [comment]
The template debug only affects to the 'debug' signals that are emited just for tests. Them does not affects anything else.

If you think that this can be done in other way, please tell me. A PR with improvements is very welcome!
