### ISSUE TITLE
Add spaceless tag as extension?

### ISSUE THREAD

**Issue by robinst** [niwinz/django-jinja#178]
Have you considered adding an extension for a `spaceless` tag? The implementation in Django templates is simple, it delegates to `strip_spaces_between_tags`:

https://github.com/django/django/blob/fff5dbe59ca629c295480693f045f03537858eee/django/template/defaulttags.py#L394-L400

If you have and decided not to, no worries :).

**Comment by niwinz** [comment]
PR is welcome!

**Comment by robinst** [comment]
I've done some work here: https://github.com/niwinz/django-jinja/compare/master...robinst:spaceless-extension?expand=1

But the test currently fails because "><" ends up being escaped. I don't know enough about how the safe handling/escaping works in Django/Jinja to do the right fix for it.

**Comment by AndreasBackx** [comment]
@robinst You have to mark the string as safe using the [Markup class.](http://jinja.pocoo.org/docs/dev/api/#jinja2.Markup)

**Comment by SimonSteinberger** [comment]
Does this work for you? We've been using this code for a long time on a high traffic site with no problems, but there may be problems/scenarios that we never encountered. The snippet simply makes use of Django's native space removal function:

from django.utils.html import strip_spaces_between_tags
class SpacelessExtension(Extension):
    tags = set(['spaceless'])
    def parse(self, parser):
        lineno = parser.stream.next().lineno
        body = parser.parse_statements(['name:endspaceless'], drop_needle=True)
        return nodes.CallBlock(self.call_method('_strip_spaces', [], [], None, None), [], [], body).set_lineno(lineno)
    def _strip_spaces(self, caller=None):
        return strip_spaces_between_tags(caller().strip())

**Comment by robinst** [comment]
Not going to work on this, closing.
