### ISSUE TITLE
Some filter are missing

### ISSUE THREAD

**Issue by dorianamouroux** [niwinz/django-jinja#182]
Hi,

I'm using django-jinja and some filters from the default DTL are missing.
I did some bind like this : 

``` python
from django_jinja import library
from django.contrib.humanize.templatetags.humanize import naturaltime as django_naturaltime

@library.filter
def naturaltime(value):
    return django_naturaltime(value)

```

Is there a better way to do it ?

**Comment by niwinz** [comment]
If you find that some filters are missing, you can do two things:

- Just declare it on your code.
- Open a PR to this project proposing include that filter in builtins.
