### ISSUE TITLE
makemessages doesn't handle escaped quotes

### ISSUE THREAD

**Issue by rangermeier** [niwinz/django-jinja#191]
The included makemessages management command shows errors when translateable strings contain escaped characters.

E.g. a template like example.html

     <a href="#" title=" {{ _('Don\t click "Delete" if unsure.')}}">{{ _('Delete') }}</a>

Gives this warning when `./manage.py makemessage` is run:

     ./templates/example.html.py:1: warning: unterminated string

This can be fixed by adding a negative lookbehind to the [regex](https://github.com/niwinz/django-jinja/blob/master/django_jinja/management/commands/makemessages.py#L56): 

    trans_real.constant_re = re.compile(r"""_\(((?:".*?(?<!\\)")|(?:'.*?(?<!\\)')).*\)""")

**Comment by niwinz** [comment]
Pushed fix to master, please, test it.

**Comment by wizpig64** [comment]
closing this issue as it looks like the fix for it has since been changed more recently anyway.
