### ISSUE TITLE
2.3.1 breaks public `Template` interface

### ISSUE THREAD

**Issue by currycoder** [niwinz/django-jinja#204]
This commit https://github.com/niwinz/django-jinja/commit/406333ce589e91debcd3a1db3f79de9cabf76524 has made it so that the `Template` object no longer has a `template` attribute.  This is a compatibility breaking change for libraries that assume it to be present - the public interface for `Template` objects is now changed.

I'm not really sure what a solution could be for this.  From what I understand, the code exhibiting the problem is in django's `IncludeNode`.  So, this is covering the case where a django template includes a jinja template?

**Comment by niwinz** [comment]
I will revert that change!

**Comment by niwinz** [comment]
Already reverted
