### ISSUE TITLE
Caching templates

### ISSUE THREAD

**Issue by gandriyko** [niwinz/django-jinja#206]
Django-jinja read template files on each request in production.
I want to cache all templates (or bytecode) in memcahed.
How can I do this?

Django==1.11.3
django-jinja==2.3.1
Jinja2==2.9.6

This doesn't help:
when I editing template, django showing last version (not cached).

```
TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        ...
        'OPTIONS': {
            'bytecode_cache': {
                'name': 'default',
                'backend': 'django_jinja.cache.BytecodeCache',
                'enabled': True,
            },
```

**Comment by niwinz** [comment]
as far as I know, jinja in contrast to the default behavior of django templates already caches the templates, so you don't need do nothing especial.
