### ISSUE TITLE
Is it possible to include DTL from .jinja?

### ISSUE THREAD

**Issue by pacahon** [niwinz/django-jinja#207]
Hello! Thanks for the app. I've noticed from commit history that it's possible to include django_jinja template from DTL with `{% include %}`. 
Is it possible (and how) to do this in reverse? I have a lot of stuff in DT syntax and want to migrate to jinja2 loader.

**Comment by niwinz** [comment]
This is posible, but this change affects  some other parts and probably will be reverted. In any case is an implementation detail. You should suppose that it is not possible.
