### ISSUE TITLE
API to programmatically add a custom filter at app time?

### ISSUE THREAD

**Issue by pleasantone** [niwinz/django-jinja#208]
I have a weird situation where I need my jinja environment to get its filters updated
once at app installation time. I list them all in a settings.py file as some of them may or may not exist at that time.

How do I update the filters directory from a django app?

**Comment by niwinz** [comment]
```
>>> from django.template import engines
>>> engines
<django.template.utils.EngineHandler object at 0x7fcc704bc518>
>>> engines["jinja2"]
<django_jinja.backend.Jinja2 object at 0x7fcc73f268d0>
>>> engines["jinja2"].env
<jinja2.environment.Environment object at 0x7fcc6e3845c0>
>>> engines["jinja2"].env.filters
```

Maybe this can help you, this is the way to access to engine on runtime, and where you can add filters at runtime.

**Comment by niwinz** [comment]
In any case, you can do it more hacky, as in jinja you can call functions, you may want to pass the functions directly in the context and then use they in the template :P

**Comment by pleasantone** [comment]
Outstanding! Thank you!

**Comment by pleasantone** [comment]
Yeah, I need compatibility with existing native jinja  so filters>functions.
