### ISSUE TITLE
Missing documentation: How to load template tags

### ISSUE THREAD

**Issue by beruic** [niwinz/django-jinja#212]
Now I am not using _django-jinja_ (yet at least), but in order to take ane educated decision and/or convince others of using a project, it is nice with good documentation that makes it easier to relate to something before you use it. The purpose of this issue is to improve _django-jinja_ on that part.

In _Django_ you have to load template tags for each template with `{% load foo bar from somelibrary %}`. What I am having a hard time figuring out is whether _django-jinja_ makes it possible to do this in a similar, easy way, or do we have to write Jinja2 extensions?

**Comment by niwinz** [comment]
WIth jinja you dont need to load them explicitly, they all are loaded in application bootstrap.

**Comment by beruic** [comment]
Where is the documentation for this? Is this the `extensions` option?

**Comment by niwinz** [comment]
This is how jinja works, nothing new is implemented.
