### ISSUE TITLE
Lack of {% debug %} support (patch included)

### ISSUE THREAD

**Issue by ShaheedHaque** [niwinz/django-jinja#213]
I've been missing the ability to {% debug %} templates since I switched, so I coded up an implementation which I'd like to propose is included with the  other extensions: [jinja_extensions.py.txt](https://github.com/niwinz/django-jinja/files/1607805/jinja_extensions.py.txt).

If preferred, I could do a PR. To avoid any confusion, note that I've also mentioned this in upstream "jinja" itself at [issue 174](https://github.com/pallets/jinja/issues/174#issuecomment-355716273).

**Comment by ShaheedHaque** [comment]
I've submitted upstream [PR 798](https://github.com/pallets/jinja/pull/798).

**Comment by niwinz** [comment]
Nice! if it is not accepted in the jinja, please submit the PR on this repo ;)

**Comment by ShaheedHaque** [comment]
Upstream looks stuck, so submitted #215 here. Please review and consider merging.

**Comment by niwinz** [comment]
Merged, thanks!

**Comment by ShaheedHaque** [comment]
Great! Are you planning a release sometime?

**Comment by ShaheedHaque** [comment]
Any chance of a release with this in it?
