### ISSUE TITLE
Django 2.0 

### ISSUE THREAD

**Issue by Alphare** [niwinz/django-jinja#219]
I noticed that Django 2.0 is not in the Travis matrix.
I'm not sure if changing the `.travis.yaml` file is enough, so I have not done a pull-request.

**Comment by auvipy** [comment]
that could be the starting point to see what fails actually

**Comment by niwinz** [comment]
Im just starting a new project right now using django2.0 so i will check if it works as expected and fix the issues if there any :D

**Comment by Alphare** [comment]
Although it is not the same as all tests passing, my current project is using Django 2.0.3 and works fine. :)

**Comment by niwinz** [comment]
Now all tests passes, and travis matrix tests is improved.
