### ISSUE TITLE
How to use this with Jinja2 in Django

### ISSUE THREAD

**Issue by JintoAntony** [niwinz/django-jinja#220]
I tried to integrate this my project, not working. Can you show me a working example ..?

**Comment by niwinz** [comment]
Yo dont need to use it with Jinja2 backend in Django, django-jinja provides its own backend. Please just follow the documentation. I have many projects using django-jinja without any problem.

**Comment by niwinz** [comment]
https://github.com/taigaio/taiga-back/blob/master/settings/common.py#L221 this is an example of configuration used in a taiga.io project.

**Comment by JintoAntony** [comment]
Let me check. Thank you for your valuable reply.  All, I am trying to do is using context processor in jinja2.

**Comment by JintoAntony** [comment]
Hi, Is there any ways to pass parameters to context processors ..?

**Comment by JintoAntony** [comment]
Is there anyway to use the load tag with jinja templates ..? because, I have this {% load widget_tweaks %} tag, and it need to get working with jinja template...

**Comment by wizpig64** [comment]
closing this as the docs explain how to set this up:

http://niwinz.github.io/django-jinja/latest/#_custom_filters_globals_constants_and_tests
