### ISSUE TITLE
Can we extend Django templates?

### ISSUE THREAD

**Issue by pykong** [niwinz/django-jinja#229]
I am using [django-adminlte2](https://github.com/adamcharnock/django-adminlte2) for the overall site structure as well as the theme for my admin pages.

Many such theme extensions exist and are a staple amongst Django users.

Hence my question:
**Is there any way we can within a jinja-template inherit from a Django-template?**

I have not been able to do it so far, as I get the known error of:
> Encountered unknown tag 'load'.

Django attempts to use jinja to render the parent template as well, which fails as Jinja obviously does not understand `{% load static %}`.

Rewriting all parent templates is not a solution due to the amount of work such endeavour would require.

Is there maybe any configuration we can change or even a possible monkey patch to mix Django and Jinja to play nicely together? If not, I feel the docs need to make it clear that we can not have heterogenous inheritance, hence severely limiting the use of any Django theme extensions.

It would be great if you could shine some light on this issue. Thanks.

**Comment by Tiagojdferreira** [comment]
I am facing a similar problem, as I have to set up an admin page keeps the admin functionalities, but uses some of our jinja templates inside.

> Rewriting all parent templates is not a solution due to the amount of work such endeavour would require.

This is what I am currently going through, and it is a pain. I would like to know if someone has an alternative?

The part I am currently strugling with is the `submit_row`.

**Comment by blueyed** [comment]
As for ignoring `{% load %}` this might be possible with a custom handler?

Have you checked / asked this over at Django?

**Comment by Dmitri-Sintsov** [comment]
There is [{% jinja %}](https://github.com/Dmitri-Sintsov/django-jinja-knockout/blob/master/django_jinja_knockout/templatetags/jinja.py) template tag, which loads a Jinja2 template from DTL and renders it with the current context. You can pass additional context data using keyword arguments.

        {% jinja "foo/some_include" %}
        {% jinja "foo/some_include" with bar="BAZZ!" baz="BING!" %}

**Comment by pykong** [comment]
@Dmitri-Sintsov 
Thanks for your answer! Works. :)
