### ISSUE TITLE
Is it possible to use settings.DATETIME_FORMAT with django-jinja?

### ISSUE THREAD

**Issue by max-block** [niwinz/django-jinja#253]
Are there any solutions how to have a default datetime formatter with jinja?

**Comment by wizpig64** [comment]
I have run into this too. django templates implicitly renders `{{ value }}` as `{{ value|date }}`, if the value is a date or datetime. From what I can tell, jinja simply runs `{{ str(value) }}`, which is not as pretty as the django date filter.

django-jinja does the work of hooking up django's date filter, so switching your templates to `{{ value|date }}` should get it to render according to the date format django settings.

I do not know of a way to instruct jinja to use a default filter for a certain type, like django implicitly does for dates, if that is what you mean.

**Comment by wizpig64** [comment]
marking this as closed as I've addressed the question. however, i would support a PR that emulates the django behavior.
