### ISSUE TITLE
What is recommended instead of context processors?

### ISSUE THREAD

**Issue by enricobarzetti** [niwinz/django-jinja#261]
The doc says that context processors are not recommended:

> As usual, this is a default list of context processors and you can skip setting them if you do not have your own. Furthermore, it is now not the recommended way to setup variables in the context and the purpose of its existence is a help for migrations.

But there is no mention of what is recommended in their place.  What is the recommended way?  This should added to the doc.

**Comment by wizpig64** [comment]
After doing some digging through the docs, the source, and the history thereof, here is the understanding I came away with:

Adding global template context via `TEMPLATES[x]["OPTIONS"]["context_processors"]` (the "django templates way") was django functionality ported to django-jinja to make transitioning from django to jinja easier, with minimal porting. A caveat was added, saying it was "not recommended" to use `context_processors` anymore, but to instead add "[Custom filters, globals, constants and tests](https://github.com/niwinz/django-jinja/blob/master/doc/content.adoc#custom-filters-globals-constants-and-tests)". I believe this is the "django-jinja way" of adding context globally.

(You can also add modify the default jinja environment in a more "jinja way", by creating a custom `jinja2.Environment`, and pointing to it with `TEMPLATES[x]["OPTIONS"]["environment"]`. The docs don't mention this option at all, but it could be useful if you were migrating the other direction, e.g. from jinja to django-jinja, and already had an Environment ready to slot in, with its own filters.)

Despite the "not recommended" wording, I do not think the `context_processors` way of doing things is deprecated. Removing it would be antithetical to django-jinja's distinction from django's built-in (and very bare-bones) jinja2 template engine: it makes transitioning from django templates to jinja templates easier, mostly by auto-importing all the nice extra features from django's template ecosystem.

I agree that the wording should be changed from how it is, to sound less disdainful of context processors, and the first warning up top should just link straight to the "Custom..." section to remove confusion. 

btw, more discussion at #235.

**Comment by enricobarzetti** [comment]
Your response was well explained and your change looks good except for a typo I commented on in the PR.
