### ISSUE TITLE
2.7.0 Release

### ISSUE THREAD

**Issue by jaykz52** [niwinz/django-jinja#269]
Judging from https://github.com/niwinz/django-jinja/commit/bdfdaa445e14b66dd266de9b77e7cf511bf8f5c5, it appears that a version 2.7.0 of `django-jinja` is in the works. `master` currently includes the changes necessary to support Django 3.1; projects depending on `django-jinja` would require pinning the `django-jinja` requirement to that SHA in order to upgrade to Django 3.1 today (which works, but is a short-term workaround). When do you expect to release 2.7.0?

**Comment by wizpig64** [comment]
@auvipy: What do you think about me applying with niwinz to be a co-maintainer on pypi and github, as you did, in issue 240? I have [some experience](https://pypi.org/user/wizpig64/) using the release tools, and would like to see this through.

**Comment by tomhamiltonstubber** [comment]
Guys please can we get a release here? It's holding us back from Django 3.1.

**Comment by wizpig64** [comment]
2.7.0 is out on pypi now, by auvipy: https://pypi.org/project/django-jinja/2.7.0/

**Comment by jaykz52** [comment]
Thank you @wizpig64 @auvipy

**Comment by auvipy** [comment]
closing as per https://github.com/niwinz/django-jinja/releases/tag/2.7.0
